services:
  backend:
    image: 'node:21.2.0'
    container_name: 'book-backend'
    working_dir: '/app'
    volumes:
      - './backend:/app'
    networks:
      - 'book-database-shared'
    ports:
      - '3000:3000'
    command: [
      'bash', '-c', 
      'npm run dev'
    ]
  frontend:
    image: 'node:21.2.0'
    container_name: 'book-frontend'
    working_dir: '/app'
    volumes:
      - './frontend:/app'
    ports:
      - '4000:4000'
    command: [
      'bash', '-c', 
      'npm run dev'
    ]

networks:
  book-database-shared:
    name: book-database-shared
    external: true